# Generated by Django 4.0 on 2023-09-08 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0037_alter_userinfo_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_to_find', models.IntegerField(null=True)),
                ('seconds_spend', models.IntegerField(null=True)),
                ('messages_shared', models.IntegerField(null=True)),
                ('talked_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.customuser')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_stats', to='chat.customuser')),
            ],
        ),
    ]
