# Generated by Django 3.2.7 on 2021-09-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210922_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
