# Generated by Django 3.2.7 on 2021-09-30 08:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210926_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgePref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('optimal_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeoCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PolitCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco', models.FloatField()),
                ('cult', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PrefWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(choices=[('FR', 'Friendship'), ('RO', 'Romantic'), ('AN', 'Anything')], default='AN', max_length=2)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Anything')], default='M', max_length=2)),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.geocoordinates')),
                ('polit_coordinates', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.politcoordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polit', models.BooleanField(default=False, max_length=200)),
                ('interests', models.BooleanField(default=False, max_length=200)),
                ('location', models.BooleanField(default=False, max_length=200)),
                ('goals', models.CharField(choices=[('FR', 'Friendship'), ('RO', 'Romantic'), ('AN', 'Anything')], default='AN', max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Anything')], default='A', max_length=2)),
                ('age', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.agepref')),
                ('weights', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.prefweights')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='chat.userinfo'),
        ),
        migrations.AddField(
            model_name='user',
            name='userPrefs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='chat.preferences'),
        ),
    ]
