# Generated by Django 3.2.7 on 2021-10-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_userinfo_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefweights',
            name='ageWeight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prefweights',
            name='intWeight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prefweights',
            name='locWeight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prefweights',
            name='polWeight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
