# Generated by Django 4.0 on 2022-01-15 05:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_userinfo_country_alter_agepref_id_alter_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room_to_join',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Inactive', max_length=200),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='loc_area',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
    ]
