# Generated by Django 4.0 on 2022-02-13 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0013_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Inactive', max_length=200)),
                ('room_to_join', models.IntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('userInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='chat.userinfo')),
                ('userPrefs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='chat.preferences')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
