# Generated by Django 4.0 on 2022-02-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_userinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agepref',
            name='max_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agepref',
            name='min_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agepref',
            name='optimal_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='geocoordinates',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='geocoordinates',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='agreeableness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='conscientiousness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='extraversion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='neuroticism',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='openness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='politcoordinates',
            name='cult',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='politcoordinates',
            name='eco',
            field=models.FloatField(null=True),
        ),
    ]
