# Generated by Django 4.0 on 2022-02-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_agepref_max_age_alter_agepref_min_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='personality',
            field=models.BooleanField(default=False, max_length=200),
        ),
    ]
