# Generated by Django 4.0 on 2022-02-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_preferences_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='anon', max_length=200),
        ),
    ]
