# Generated by Django 4.0 on 2022-03-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(to='chat.Message')),
                ('participants', models.ManyToManyField(blank=True, related_name='chats', to='chat.CustomUser')),
            ],
        ),
    ]
