# Generated by Django 4.0 on 2022-03-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_remove_message_chat_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date sent'),
        ),
    ]
