# Generated by Django 4.0 on 2022-03-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_alter_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ignoredUsers',
            field=models.ManyToManyField(related_name='usersIgnoredBy', to='chat.CustomUser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sentFriendRequests',
            field=models.ManyToManyField(related_name='receivedFriendRequests', to='chat.CustomUser'),
        ),
    ]
