# Generated by Django 4.0 on 2022-03-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_customuser_ignoredusers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(to='chat.CustomUser'),
        ),
    ]
