# Generated by Django 4.0 on 2022-04-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
