# Generated by Django 4.0 on 2022-04-02 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_remove_customuser_description_userinfo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date started talking')),
                ('chattedWith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='historicalChats',
            field=models.ManyToManyField(to='chat.HistoricalChat'),
        ),
    ]
