# Generated by Django 4.0 on 2022-04-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
