# Generated by Django 4.0 on 2023-07-03 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_alter_userinfo_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='historicalchat',
            name='chattedWith',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='SearchingInstance',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='ignoredUsers',
            new_name='ignored_users',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='historicalChats',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sentFriendRequests',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userInfo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userPrefs',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='chat.userinfo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_prefs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='chat.preferences'),
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='HistoricalChat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
