# Generated by Django 4.0 on 2023-07-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_2',
        ),
    ]
