# Generated by Django 4.0 on 2023-08-31 07:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_remove_chat_user_1_remove_chat_user_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
